### ISSUE TITLE
Errores varios Win10

### ISSUE THREAD

**Issue by jorge705** [DoddyHackman/DH_Rat#1]
Sitema: Windows 10 64bits
Error: 
1- Cuando creo el servidor con las opciones por defecto me aparece un mensaje de error: ("31/12/1969 21:00:00" is not a valid date and time), pero el servidor sigue corriendo en la memoria, pero tampoco conecta (puse de direccion 127.0.0.1)

2- Al desactivar la opcion "DateTime" me aparece el siguiente error: "Asynchronous socket error 10061", pero el servidor se injecta bien y sigue corriendo, pero tampoco conecta

nose si sera problema mio o error de programacion

**Comment by DoddyHackman** [comment]
puff , lo acabo de probar con todo lo que dijiste y funciona bien en Seven 32 y 64 bits , debe ser que no es compatible con Windows 10 , ahora que lo pienso mejor en Win 10 deben verificar que la fecha sea real por eso el error , gracias por probar la herramienta.

**Comment by DoddyHackman** [comment]
Cuando tenga tiempo hago un fix para Windows 10.

**Comment by DoddyHackman** [comment]
hola de nuevo ,estuve probando y el problema es que el servidor devuelve "Asynchronous socket error 10061" y no se conecta es cuando no se ha activado el servidor principal , osea "start server" en el builder , ¿ lo has hecho verdad ? , solo es esa duda para tener en cuenta.

**Comment by jorge705** [comment]
ohh amigo, no habia visto esa opcion, estaba escondida xDD, ahora si pude iniciar el servidor en windows 10 desactivando "DateTime", gracias, problema resuelto

**Comment by fairylovehn127** [comment]
Can we test with 2 difference computer?
I test with different computer and message Asynchronous socket error 10061 was shown.

**Comment by DoddyHackman** [comment]
Ese error indica que el servidor nunca abrio el puerto , tenes que abrir el puerto en el router y en el firewall para que pueda iniciar la conexion desde otra computadora , eso es algo que se hace en todos los rats , busca informacion en google.
